### ISSUE TITLE
missing requirement

### ISSUE THREAD

**Issue by andreasbinder** [Mchristos/empowerment#5]
First of all, thanks for the informative article, I learnt a lot by reading it.

When I create my virtualenvironment and ran setup.py I noticed that matplotlib is not getting installed when executing your script. You might consider updating that. After installing it manually it worked.

**Comment by Mchristos** [comment]
Thank you @andreasbinder! Will update 👍

**Comment by Mchristos** [comment]
Added matplotlib to requirements, closing issue
